# Generated by bincast — https://github.com/benelser/bincast
# Homebrew formula for bincast
class Bincast < Formula
  desc "Ship your Rust binary to every package manager with one command"
  homepage "https://github.com/benelser/bincast"
  version "0.1.11"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/benelser/bincast/releases/download/v#{version}/bincast-aarch64-apple-darwin.tar.gz"
      sha256 "779ead18bc3ddfbcfde297b2693650af9ab774e174a33677e395631297ec3032"
    end
    if Hardware::CPU.intel?
      url "https://github.com/benelser/bincast/releases/download/v#{version}/bincast-x86_64-apple-darwin.tar.gz"
      sha256 "72c81e5a89dfe18155e143fe62d9f259d1407ec6433be5b181794d70badb30df"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/benelser/bincast/releases/download/v#{version}/bincast-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "25c675157131319c717013776c91fff0489a00dcaf96bbd7563a74cf42401814"
    end
    if Hardware::CPU.intel?
      url "https://github.com/benelser/bincast/releases/download/v#{version}/bincast-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "7e98d4e75d567ad27fb9d8b22868b198795cf76a0217a84bd51832065a00f725"
    end
  end

  def install
    bin.install "bincast"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/bincast --version")
  end
end
