# Generated by bincast — https://github.com/benelser/bincast
# Homebrew formula for bincast
class Bincast < Formula
  desc "Ship your Rust binary to every package manager with one command"
  homepage "https://github.com/benelser/bincast"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/benelser/bincast/releases/download/v#{version}/bincast-aarch64-apple-darwin.tar.gz"
      sha256 ""
    end
    if Hardware::CPU.intel?
      url "https://github.com/benelser/bincast/releases/download/v#{version}/bincast-x86_64-apple-darwin.tar.gz"
      sha256 ""
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/benelser/bincast/releases/download/v#{version}/bincast-aarch64-unknown-linux-gnu.tar.gz"
      sha256 ""
    end
    if Hardware::CPU.intel?
      url "https://github.com/benelser/bincast/releases/download/v#{version}/bincast-x86_64-unknown-linux-gnu.tar.gz"
      sha256 ""
    end
  end

  def install
    bin.install "bincast"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/bincast --version")
  end
end
